export const info: string;
export const site_name: string;
export const amount: string;
export const order: string;
export const description: string;
export const dueDate: string;
export const subscription: string;
export const help: string;
export const _hide: string;
