export const loader: string;
export const growth: string;
export const fadein: string;
export const slidedown: string;
export const slideup: string;
export const popup: string;
export const rotatein: string;
export const rotateout: string;
export const shake: string;
