const GET_INVOICE = 'GET_INVOICE';
const CREATE_INVOICE = 'CREATE_INVOICE';
const FAILED_CREATE_INVOICE = 'FAILED_CREATE_INVOICE';

export {
    GET_INVOICE,
    CREATE_INVOICE,
    FAILED_CREATE_INVOICE
}