const SET_STATUS = 'SET_STATUS';
const SET_TOKEN = 'SET_TOKEN';
const SET_INTERACTION_DATA = 'SET_INTERACTION_DATA';
const SET_PAYMENT_ERROR = 'SET_PAYMENT_ERROR';

export {
    SET_STATUS,
    SET_TOKEN,
    SET_INTERACTION_DATA,
    SET_PAYMENT_ERROR
}
