const UPDATE_CONTAINER_SIZE = 'UPDATE_CONTAINER_SIZE';
const SET_DEFAULT_EMAIL = 'SET_DEFAULT_EMAIL';
const SET_CARD_FORM_DATA = 'SET_CARD_FORM_DATA';
const SET_CARD_NUMBER_VALUE = 'SET_CARD_NUMBER';
const SET_CARD_EXP_VALUE = 'SET_CARD_EXP_VALUE';
const SET_CARD_CVV_VALUE = 'SET_CARD_CVV_VALUE';
const SET_CARD_HOLDER_VALUE = 'SET_CARD_HOLDER_VALUE';
const SET_EMAIL_VALUE = 'SET_EMAIL_VALUE';
const VALIDATE_FORM = 'VALIDATE_FORM';

export {
    UPDATE_CONTAINER_SIZE,
    SET_DEFAULT_EMAIL,
    SET_CARD_FORM_DATA,
    SET_CARD_NUMBER_VALUE,
    SET_CARD_EXP_VALUE,
    SET_CARD_CVV_VALUE,
    SET_CARD_HOLDER_VALUE,
    SET_EMAIL_VALUE,
    VALIDATE_FORM,
}
