const UPDATE_CONTAINER_SIZE = 'UPDATE_CONTAINER_SIZE';
const SET_DEFAULT_EMAIL = 'SET_DEFAULT_EMAIL';
const SET_CARD_FORM_DATA = 'SET_CARD_FORM_DATA';
const SET_CARD_NUMBER_VALUE = 'SET_CARD_NUMBER';
const SET_CARD_EXP_VALUE = 'SET_CARD_EXP_VALUE';
const SET_CARD_CVV_VALUE = 'SET_CARD_CVV_VALUE';
const SET_CARD_HOLDER_VALUE = 'SET_CARD_HOLDER_VALUE';
const SET_EMAIL_VALUE = 'SET_EMAIL_VALUE';
const SET_AMOUNT_VALUE = 'SET_AMOUNT_VALUE';
const SET_AMOUNT_TYPE = 'SET_AMOUNT_TYPE';
const SET_EMAIL_VISIBILITY = 'SET_EMAIL_VISIBILITY';
const SET_AMOUNT_VISIBILITY = 'SET_AMOUNT_VISIBILITY';
const SET_CARD_SET_VISIBILITY = 'SET_CARD_SET_VISIBILITY';
const SET_EMAIL_REQUIRED = 'SET_EMAIL_REQUIRED';
const SET_AMOUNT_REQUIRED = 'SET_AMOUNT_REQUIRED';
const SET_CARD_SET_REQUIRED = 'SET_CARD_SET_REQUIRED';
const SET_ACTIVE_FORM = 'SET_ACTIVE_FORM';
const SET_PREVIOUS_FORM = 'SET_PREVIOUS_FORM';
const VALIDATE_FORM = 'VALIDATE_FORM';
const RESET_VALIDATION = 'RESET_VALIDATION';

export {
    UPDATE_CONTAINER_SIZE,
    SET_ACTIVE_FORM,
    SET_PREVIOUS_FORM,
    SET_DEFAULT_EMAIL,
    SET_CARD_FORM_DATA,
    SET_CARD_NUMBER_VALUE,
    SET_CARD_EXP_VALUE,
    SET_CARD_CVV_VALUE,
    SET_CARD_HOLDER_VALUE,
    SET_EMAIL_VALUE,
    SET_AMOUNT_VALUE,
    SET_AMOUNT_TYPE,
    SET_EMAIL_VISIBILITY,
    SET_AMOUNT_VISIBILITY,
    SET_CARD_SET_VISIBILITY,
    SET_EMAIL_REQUIRED,
    SET_AMOUNT_REQUIRED,
    SET_CARD_SET_REQUIRED,
    VALIDATE_FORM,
    RESET_VALIDATION
}
