const START = 'START';
const SET_PAYMENT_ERROR = 'SET_PAYMENT_ERROR';
const PROCESS_PAYMENT = 'PROCESS_PAYMENT';
const PROCESS_INVOICE_TEMPLATE = 'PROCESS_INVOICE_TEMPLATE';
const INTERACT_PAYMENT = 'INTERACT_PAYMENT';
const RESET = 'RESET';
const FINISH = 'FINISH';
const RESUME_PAYMENT = 'RESUME_PAYMENT';

export {
    START,
    PROCESS_INVOICE_TEMPLATE,
    PROCESS_PAYMENT,
    INTERACT_PAYMENT,
    RESUME_PAYMENT,
    RESET,
    FINISH,
    SET_PAYMENT_ERROR
}
