export enum TypeKeys {
    SET_RESULT = 'SET_RESULT',
    GET_APP_CONFIG = 'GET_APP_CONFIG',
    GET_INVOICE_TEMPLATE = 'GET_INVOICE_TEMPLATE',
    GET_INVOICE = 'GET_INVOICE',
    INIT_STAGE_START = 'INIT_STAGE_START',
    INIT_STAGE_DONE = 'INIT_STAGE_DONE',
    SET_ERROR = 'SET_ERROR'
}
