export enum TypeKeys {
    SET_RESULT = 'SET_RESULT',
    GET_APP_CONFIG = 'GET_APP_CONFIG',
    GET_LOCALE = 'GET_LOCALE',
    GET_INVOICE_EVENTS = 'GET_INVOICE_EVENTS',
    GET_INVOICE_TEMPLATE = 'GET_INVOICE_TEMPLATE',
    GET_INVOICE = 'GET_INVOICE',
    SET_INVOICE = 'SET_INVOICE',
    GET_INVOICE_PAYMENT_METHODS = 'GET_INVOICE_PAYMENT_METHODS',
    GET_INVOICE_PAYMENT_METHODS_BY_TEMPLATE_ID = 'GET_INVOICE_PAYMENT_METHODS_BY_TEMPLATE_ID',
    SET_ERROR = 'SET_ERROR',
    SET_FORMS_FLOW = 'SET_FORMS_FLOW',
    LIFECYCLE_CHANGE_STEP_STATUS = 'LIFECYCLE_CHANGE_STEP_STATUS',
    LIFECYCLE_CHANGE_STAGE_STATUS = 'LIFECYCLE_CHANGE_STAGE_STATUS'
}
