export enum TypeKeys {
    SET_RESULT = 'SET_RESULT',
    GET_APP_CONFIG = 'GET_APP_CONFIG',
    GET_LOCALE = 'GET_LOCALE',
    GET_INVOICE_TEMPLATE = 'GET_INVOICE_TEMPLATE',
    GET_INVOICE = 'GET_INVOICE',
    GET_INVOICE_PAYMENT_METHODS = 'GET_INVOICE_PAYMENT_METHODS',
    GET_INVOICE_PAYMENT_METHODS_BY_TEMPLATE_ID = 'GET_INVOICE_PAYMENT_METHODS_BY_TEMPLATE_ID',
    INIT_STAGE_START = 'INIT_STAGE_START',
    INIT_STAGE_DONE = 'INIT_STAGE_DONE',
    SET_ERROR = 'SET_ERROR',
    SET_FORMS_FLOW = 'SET_FORMS_FLOW',
    FORMS_FLOW_INIT_DONE = 'FORMS_FLOW_INIT_DONE',
    INIT_STAGE_CHANGE = 'INIT_STAGE_CHANGE'
}
